/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class Registro extends javax.swing.JFrame {

         //Variables relacionadas con la Base de Datos :D
    PreparedStatement stm;
  Connection connDBC = null;
    PreparedStatement pst = null;
    ResultSet resultado = null;
    //Objeto relacionado con  la base de Datos y Aqui 
    Conexionar dbc = new Conexionar();
    
    //Estos son las variables que seran llenadas con la informacion del usuario
    String nombre;
    String password;
    String telefono;
    String conPass;
    
    //Este es uno de esos Booleanos traidores
    boolean UserExists;
   
    
    
    public Registro() {
        initComponents();
         this.setLocationRelativeTo(null);
        this.setResizable(false);
//         Image icon = new ImageIcon(getClass().getResource("../Imagenes/Iconos/SunflowerIcon.png")).getImage();
//         setIconImage(icon);
    }
    
    
    
    //METODOS BASE DE DATOS
        public void Añadir_usuario(String nombre, String contraseña,  String telefono, String admin ){
       try {
            connDBC = dbc.conectar();
            String SQL = "INSERT INTO usuarios (nombre, contraseña, telefono, admin, fecha_creacion) VALUES(?, ?, ?, ?, now() )";
            
           stm = connDBC.prepareStatement(SQL);
           
            stm.setString(1, nombre);                        
            stm.setString(2, contraseña);
            stm.setString(3, telefono);
            stm.setString(4, admin );
            
            stm.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Usuario registrado.");
            this.setVisible(false);
            new Login().setVisible(true);
           connDBC.close();
        } catch (SQLException ex) {
            Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Hubo un error al ejecutar la consulta: \n" + ex);
            
        }
       
       }
        //Buscar si el nombre de ese Usuario se encuentra en la BD
         public boolean UserAlreadyRegistered(String nombre){
                                try {
                                    connDBC= dbc.conectar();
                                    String SQLselect = "SELECT nombre FROM public.usuarios WHERE nombre = ?";
                                    pst = connDBC.prepareStatement(SQLselect);
                                    pst.setString(1, nombre);
                                    resultado = pst.executeQuery();
                                    
                                    //Esta fue una de esas autocorreciones de netbeans que iban con if que sea lo que Dios quiera
                                    UserExists = resultado.next();

                                } catch (SQLException ex) {
                                    Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
                                }
                                
                                return UserExists;
        
    }
        
        
        //METODOS NO TAN BASE DE DATOS
               //Te faltan las restricciones apropiadas para esto
        boolean HayLetrasTel(String evt) {
            boolean validar = false;
//            String expression = "([a-zA-Z]+)|(['()+,\\-.=]+)";
            String expression = "([a-zA-Z]+)|(['()+,\\.=]+)";
            if(evt.matches(expression)){
               validar = true;
           }
            return validar;
       }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form
     * Editor.
     */
    @SuppressWarnings("unchecked")
             // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
             private void initComponents() {

                          jSeparator3 = new javax.swing.JSeparator();
                          jPanel1 = new javax.swing.JPanel();
                          jLabel1 = new javax.swing.JLabel();
                          jPanel2 = new javax.swing.JPanel();
                          jLabel3 = new javax.swing.JLabel();
                          jLabel4 = new javax.swing.JLabel();
                          jLabel5 = new javax.swing.JLabel();
                          jLabel6 = new javax.swing.JLabel();
                          jSeparator1 = new javax.swing.JSeparator();
                          jSeparator2 = new javax.swing.JSeparator();
                          jSeparator4 = new javax.swing.JSeparator();
                          Register_Button = new javax.swing.JLabel();
                          jLabel8 = new javax.swing.JLabel();
                          jLabel9 = new javax.swing.JLabel();
                          jLabel10 = new javax.swing.JLabel();
                          txt_user = new javax.swing.JTextField();
                          txt_pass = new javax.swing.JTextField();
                          txt_tel = new javax.swing.JTextField();
                          jLabel7 = new javax.swing.JLabel();
                          jLabel11 = new javax.swing.JLabel();
                          jPanel3 = new javax.swing.JPanel();
                          jLabel2 = new javax.swing.JLabel();
                          jLabel12 = new javax.swing.JLabel();
                          jSeparator5 = new javax.swing.JSeparator();
                          txt_ConPass = new javax.swing.JTextField();
                          lbl_conPass = new javax.swing.JLabel();
                          lbl_tel1 = new javax.swing.JLabel();
                          lbl_nombre = new javax.swing.JLabel();

                          jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

                          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                          setBackground(new java.awt.Color(255, 255, 255));

                          jPanel1.setBackground(new java.awt.Color(255, 255, 255));
                          jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                          jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/UsuarioRegister.png"))); // NOI18N
                          jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

                          jPanel2.setBackground(new java.awt.Color(89, 171, 227));

                          jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
                          jLabel3.setForeground(new java.awt.Color(255, 255, 255));
                          jLabel3.setText("Contraseña");

                          jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
                          jLabel5.setForeground(new java.awt.Color(255, 255, 255));
                          jLabel5.setText("Teléfono");

                          jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
                          jLabel6.setForeground(new java.awt.Color(255, 255, 255));
                          jLabel6.setText("Nombre de usuario");

                          jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

                          jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

                          jSeparator4.setForeground(new java.awt.Color(255, 255, 255));

                          Register_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/Register.png"))); // NOI18N
                          Register_Button.setToolTipText("Registrar usuario.");
                          Register_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                          Register_Button.addMouseListener(new java.awt.event.MouseAdapter() {
                                       public void mouseClicked(java.awt.event.MouseEvent evt) {
                                                    Register_ButtonMouseClicked(evt);
                                       }
                          });

                          txt_user.setBackground(new java.awt.Color(89, 171, 227));
                          txt_user.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
                          txt_user.setForeground(new java.awt.Color(255, 255, 255));
                          txt_user.setBorder(null);
                          txt_user.addActionListener(new java.awt.event.ActionListener() {
                                       public void actionPerformed(java.awt.event.ActionEvent evt) {
                                                    txt_userActionPerformed(evt);
                                       }
                          });

                          txt_pass.setBackground(new java.awt.Color(89, 171, 227));
                          txt_pass.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
                          txt_pass.setForeground(new java.awt.Color(255, 255, 255));
                          txt_pass.setBorder(null);

                          txt_tel.setBackground(new java.awt.Color(89, 171, 227));
                          txt_tel.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
                          txt_tel.setForeground(new java.awt.Color(255, 255, 255));
                          txt_tel.setBorder(null);
                          txt_tel.addActionListener(new java.awt.event.ActionListener() {
                                       public void actionPerformed(java.awt.event.ActionEvent evt) {
                                                    txt_telActionPerformed(evt);
                                       }
                          });

                          jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 0, 48)); // NOI18N
                          jLabel7.setForeground(new java.awt.Color(255, 255, 255));
                          jLabel7.setText("Registro");

                          jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                          jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
                                       public void mouseClicked(java.awt.event.MouseEvent evt) {
                                                    jLabel11MouseClicked(evt);
                                       }
                          });

                          jPanel3.setBackground(new java.awt.Color(107, 185, 240));
                          jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                          jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
                                       public void mouseClicked(java.awt.event.MouseEvent evt) {
                                                    jPanel3MouseClicked(evt);
                                       }
                          });

                          jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
                          jLabel2.setForeground(new java.awt.Color(255, 255, 255));
                          jLabel2.setText("Iniciar Sesión");
                          jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                          jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
                                       public void mouseClicked(java.awt.event.MouseEvent evt) {
                                                    jLabel2MouseClicked(evt);
                                       }
                          });

                          javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                          jPanel3.setLayout(jPanel3Layout);
                          jPanel3Layout.setHorizontalGroup(
                                       jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                    .addContainerGap(27, Short.MAX_VALUE)
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(22, 22, 22))
                          );
                          jPanel3Layout.setVerticalGroup(
                                       jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel2)
                                                    .addContainerGap())
                          );

                          jLabel12.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
                          jLabel12.setForeground(new java.awt.Color(255, 255, 255));
                          jLabel12.setText("Confirmar contraseña");

                          jSeparator5.setForeground(new java.awt.Color(255, 255, 255));

                          txt_ConPass.setBackground(new java.awt.Color(89, 171, 227));
                          txt_ConPass.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
                          txt_ConPass.setForeground(new java.awt.Color(255, 255, 255));
                          txt_ConPass.setBorder(null);

                          lbl_conPass.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
                          lbl_conPass.setForeground(new java.awt.Color(255, 255, 255));

                          lbl_tel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
                          lbl_tel1.setForeground(new java.awt.Color(255, 255, 255));

                          lbl_nombre.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
                          lbl_nombre.setForeground(new java.awt.Color(255, 255, 255));

                          javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                          jPanel2.setLayout(jPanel2Layout);
                          jPanel2Layout.setHorizontalGroup(
                                       jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel11)
                                                    .addContainerGap())
                                       .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addContainerGap()
                                                    .addComponent(jLabel8)
                                                    .addGap(80, 80, 80)
                                                    .addComponent(jLabel4)
                                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                       .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addGap(59, 59, 59)
                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                 .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                 .addComponent(jLabel9))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                 .addGroup(jPanel2Layout.createSequentialGroup()
                                                                              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                           .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                           .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                                        .addGap(10, 10, 10)
                                                                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                     .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                                                                  .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                  .addGap(18, 18, 18)
                                                                                                                                  .addComponent(lbl_conPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                                                                     .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                                                                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                               .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                               .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                               .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                               .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                               .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                               .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                                                                                            .addGap(4, 4, 4)
                                                                                                                                                            .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                               .addComponent(txt_ConPass, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                               .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                  .addGap(0, 0, Short.MAX_VALUE))
                                                                                                                     .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                                                                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                               .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                               .addComponent(txt_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                  .addComponent(lbl_tel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                                                                     .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                                                                  .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                  .addGap(42, 42, 42)
                                                                                                                                  .addComponent(lbl_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                                                                  .addGap(9, 9, 9)))))
                                                                              .addContainerGap())
                                                                 .addGroup(jPanel2Layout.createSequentialGroup()
                                                                              .addGap(18, 18, 18)
                                                                              .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                                                                              .addComponent(Register_Button)
                                                                              .addGap(19, 19, 19))))
                          );
                          jPanel2Layout.setVerticalGroup(
                                       jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                    .addContainerGap()
                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                 .addGroup(jPanel2Layout.createSequentialGroup()
                                                                              .addGap(0, 0, Short.MAX_VALUE)
                                                                              .addComponent(jLabel10)
                                                                              .addGap(23, 23, 23)
                                                                              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                           .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                                                                                     .addGap(34, 34, 34)
                                                                                                                     .addComponent(jLabel8)
                                                                                                                     .addGap(66, 66, 66))
                                                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                                                     .addGap(59, 59, 59)
                                                                                                                     .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                  .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                  .addComponent(jLabel9))
                                                                                                                     .addGap(110, 110, 110)))
                                                                                           .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                                        .addComponent(jLabel4)
                                                                                                        .addContainerGap())))
                                                                 .addGroup(jPanel2Layout.createSequentialGroup()
                                                                              .addComponent(jLabel11)
                                                                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                                                                        .addComponent(jLabel7)
                                                                                                        .addGap(21, 21, 21)
                                                                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                     .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                     .addComponent(lbl_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                     .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                                                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                  .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                  .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                                  .addComponent(jLabel3)
                                                                                                                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                  .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                  .addGap(10, 10, 10)
                                                                                                                                  .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                                  .addComponent(jLabel12)
                                                                                                                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                  .addComponent(txt_ConPass, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                  .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                     .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                                                                  .addGap(110, 110, 110)
                                                                                                                                  .addComponent(lbl_conPass, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                        .addComponent(jLabel5)
                                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                        .addComponent(txt_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                           .addComponent(lbl_tel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                              .addGap(38, 38, 38)
                                                                              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                           .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                           .addComponent(Register_Button))
                                                                              .addGap(25, 25, 25))))
                          );

                          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                          getContentPane().setLayout(layout);
                          layout.setHorizontalGroup(
                                       layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addContainerGap())
                          );
                          layout.setVerticalGroup(
                                       layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                       .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                          );

                          pack();
             }// </editor-fold>//GEN-END:initComponents

    private void txt_telActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telActionPerformed
        
        
        
        
    }//GEN-LAST:event_txt_telActionPerformed

    private void Register_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Register_ButtonMouseClicked

        nombre = txt_user.getText();
        password = txt_pass.getText();
        telefono = txt_tel.getText();
        conPass = txt_ConPass.getText();
        
        
        if (UserAlreadyRegistered(nombre) ){
            lbl_nombre.setText("Ese nombre de usuario ya existe.");
            
        }else {
        
        
       
        
        if (         !password.equals(conPass)    ) {
        
            
                    lbl_conPass.setText("Las contraseñas ingresadas no coinciden.");
            
        }else {
            
          if(      HayLetrasTel(telefono)   ) {
            
                lbl_tel1.setText("Su número de teléfono contiene carácteres no deseados.");
                
            }else {
            
            
            
        if(              !nombre.equals("")  &&  !password.equals("")   &&   !telefono.equals("")                ) {
            
          
            
        Añadir_usuario(nombre, password, telefono, "NO");
            }
        else {
        JOptionPane.showMessageDialog(this, "Porfavor complete todos los campos");
        }
                  }   
        }
        //1
        }
        
    }//GEN-LAST:event_Register_ButtonMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        
        
        
        new Login().setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel11MouseClicked

             private void txt_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_userActionPerformed
                          // TODO add your handling code here:
             }//GEN-LAST:event_txt_userActionPerformed

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
     new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jPanel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Widnows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

             // Variables declaration - do not modify//GEN-BEGIN:variables
             private javax.swing.JLabel Register_Button;
             private javax.swing.JLabel jLabel1;
             private javax.swing.JLabel jLabel10;
             private javax.swing.JLabel jLabel11;
             private javax.swing.JLabel jLabel12;
             private javax.swing.JLabel jLabel2;
             private javax.swing.JLabel jLabel3;
             private javax.swing.JLabel jLabel4;
             private javax.swing.JLabel jLabel5;
             private javax.swing.JLabel jLabel6;
             private javax.swing.JLabel jLabel7;
             private javax.swing.JLabel jLabel8;
             private javax.swing.JLabel jLabel9;
             private javax.swing.JPanel jPanel1;
             private javax.swing.JPanel jPanel2;
             private javax.swing.JPanel jPanel3;
             private javax.swing.JSeparator jSeparator1;
             private javax.swing.JSeparator jSeparator2;
             private javax.swing.JSeparator jSeparator3;
             private javax.swing.JSeparator jSeparator4;
             private javax.swing.JSeparator jSeparator5;
             private javax.swing.JLabel lbl_conPass;
             private javax.swing.JLabel lbl_nombre;
             private javax.swing.JLabel lbl_tel1;
             private javax.swing.JTextField txt_ConPass;
             private javax.swing.JTextField txt_pass;
             private javax.swing.JTextField txt_tel;
             private javax.swing.JTextField txt_user;
             // End of variables declaration//GEN-END:variables
}
